language: ruby
script: "bundle exec rake test:units"
sudo: false
cache: bundler
before_install:
  # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
  - gem update --system
  - gem install bundler

rvm:
- 2.6.5
- 2.5
- 2.4
- 2.3

gemfile:
- Gemfile.rails60
- Gemfile.rails52
- Gemfile.rails51
- Gemfile.rails50
- Gemfile.rails42

matrix:
  exclude:
    - rvm: 2.3
      gemfile: Gemfile.rails60
    - rvm: 2.4
      gemfile: Gemfile.rails60

notifications:
  email:
    on_success: never
    on_failure: always
